### PR TITLE
Make tt_news_div methods static

### PR DESCRIPTION
**Pull request by sgrossberndt**
All usages of tt_news_div are static in the extension but the functions itself were not. In PHP 5.6 this leads to PHP Runtime Deprecation Notice filling the sys_log:
"Non-static method tx_ttnews_div::getSubCategories() should not be called statically, assuming $this from incompatible context"
Make the tt_news_div methods static to prevent this.
While at it improve the PHPDoc and fix minor issues.

### CODE REVIEW

**Comment by julianxhokaxhiu** [comment]
Is it possible to backport this pull request also for 6.2.x version?

**Comment by sgrossberndt** [comment]
That indeed would be great.

**Comment by bastians** [comment]
That would be awesome!

**Comment by neufeind** [comment]
Backport would indeed be great.
Just for reference: Ticket on forge.typo3.org is at https://forge.typo3.org/issues/63761

**Pull request merged**
