### PR TITLE
[BUGFIX] #58 Respect storage_pid if useStoragePid is enabled in EXTCONF

### PR DESCRIPTION
**Pull request by LeoniePhiline**
NOTE: Enabling useStoragePid means you need to have compatibility6 installed.
@see https://docs.typo3.org/typo3cms/extensions/core/Changelog/7.4/Deprecation-65790-PagesStoragePidDeprecated.html

\TYPO3\CMS\Backend\Utility\BackendUtility::getTCEFORM_TSconfig() can no
longer be used for determining the storage_pid, since this field is no
longer loaded by the internally used
\TYPO3\CMS\Backend\Utility\BackendUtility::getPageForRootline().

We are now figuring out the storage Pid ourselves, by traversing the
rootline.

### CODE REVIEW

**Comment by derhecht** [comment]
so compatibility6 has to be installed to work properly? no way!

**Comment by LeoniePhiline** [comment]
Else you'll have to remove or rewrite all the useStoragePid related code.

Your extension offers use of the storage pid which has been moved into compatibility6. 

If you don't want this optional compat feature to keep using tt_news with useStoragePid, then you've got lots of dead code in there.

**Comment by LeoniePhiline** [comment]
Still this code only requires compatibility6 IF anyone wants or needs to keep using a setup involving tt_news and category sources defined by page.storage_pid.
If the extconf switch useStoragePid is off by default, then no compatibility6 is required. 

A hint in the extconf labels and an "is compatibility6 installed?" when useStoragePid is found to be enabled, could help users.

**Comment by derhecht** [comment]
see approach in https://github.com/rupertgermann/tt_news/pull/60

**Pull request closed without merging**
