### PR TITLE
[BUGFIX] #46 Fix JS in New Admin

### PR DESCRIPTION
**Pull request by derhecht**
Please approve.

Created for https://github.com/rupertgermann/tt_news/issues/46

### CODE REVIEW

**Comment by LeoniePhiline** [comment]
Having the same issue here - Please approve this pull request! :)

**Comment by derhecht** [comment]
@LeoniePhiline you can approve by just checkout this PR, test and approve (by comment here) when it works.

**Comment by LeoniePhiline** [comment]
@derhecht Thanks - will let you know.

**Comment by LeoniePhiline** [comment]
@derhecht 
Works for me.

screenshot_20170307_155549

Note: Form controls are all too big for the available space - you can see that in the attached screenshot.

screenshot_20170307_155532

**Pull request merged**
